# Generated by Django 4.1.2 on 2022-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
