# Generated by Django 4.1.2 on 2022-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdapp', '0003_alter_stock_mode_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='type',
            field=models.CharField(choices=[('CONSUMABLE', 'CONSUMABLE'), ('NON-COMSUMABLE', 'NON-COMSUMABLE')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salebill',
            name='Mode_of_delivery',
            field=models.CharField(choices=[('BY-HAND', 'BY-HAND'), ('COURIER', 'COURIER'), ('OTHER', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'GOOD'), ('TORN', 'TORN'), ('DAMAGED', 'DAMAGED')], max_length=50),
        ),
    ]
