# Generated by Django 4.1.2 on 2022-10-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdapp', '0005_category_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
    ]
