# Generated by Django 4.1.2 on 2022-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdapp', '0007_category_description_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('CONSUMABLE', 'CONSUMABLE'), ('NON-COMSUMABLE', 'NON-COMSUMABLE')], max_length=50),
        ),
    ]
